global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['textcat-app-production.up.railway.app:443']
    scheme: https
